### ISSUE TITLE
GAMES 201 TODO items

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1016]
This issue summarizes a few features that will help improve the user experience of students in [GAMES 201](http://games-cn.org/games201/). These issues are good starting points for GAMES 201 TAs to participate in Taichi developments, so they should be ideally implemented by GAMES 201 TAs. 

## Items
Before June 1
 - [x] Better `print` statement in Taichi kernels for debugging (#923, done in #1038)
 - [x] Standardize math library (Stage 1) (#833, done in #1091)
 - [x] Handy tensor definitions for negative coordinates (#938, WIP) 
 - [x] Huge Linux package size (#1017, done)
 - [x] Fix access out-of-bound checks in SNode accessors (#1025, done)
 - [x] Disable `gdb` trigger by default on release mode (#1088, done in #1093)
 - [x] Restore `gui.text` so that students can draw text on screen (for total potential energy etc) (#1045, done in #1070)
 - [x] Allow running examples using `ti example` (#775, done in #1010)
 - [x] Separate `ti.Vector` from `ti.Matrix` (#940. done in #1046)
 - [x] Make `ti.Vector.cross` support 2D vectors, return scalar (done in #1068)

Before June 13
 - [x] Video generation tutorial (#1116)
 - [x] Bound checks for negative coordinates (#938)
 - [x] Export to `.ply` so that students can view particles in Houdini/Blender
 - [x] Optimize reduction (@yuanming-hu)

Low priority:
 - [x] Make Matrix.\_\_init\_\_ less response by introducing multiple initializers (#1095)
 - [ ] Obsolete `ti.cfg` (#455, WIP)
 - [ ] Further standardize math library (Stage 2) (#833)
 - [ ] Any installation/compatibility issues

**Comment by rexwangcc** [comment]
> Export to .bgeo

Have only used it to work with maya pdb files, but it seems [partio](http://partio.us/documentation.html) also supports writing to `.bgeo` easily.

**Comment by yuanming-hu** [comment]
> > Export to .bgeo
> 
> Have only used it to work with maya pdb files, but it seems [partio](http://partio.us/documentation.html) also supports writing to `.bgeo` easily.

An old issue on this: https://github.com/taichi-dev/taichi/issues/148
Right, we only need a very small subset of `partio`.

**Comment by FantasyVR** [comment]
Let me try to solve the second problem: `Standard math library`

TA: Peng Yu

**Comment by archibate** [comment]
Thank for all your valuable discussions! Btw, would you mind to open a [milestone](https://help.github.com/en/github/managing-your-work-on-github/about-milestones) for issues like this?

**Comment by MarisaKirisame** [comment]
BTW Is the talk gonna get recorded? I dont wanna stay up that late/wake up that early to look at them.

**Comment by archibate** [comment]
+1, monday is a busy day to me. If we do screen recording then it's possible for college stduents like me to watch it later when they are ready, also helps people in different time zones.

**Comment by Rullec** [comment]
Hi All,
The 3rd issue in this list [#938 ](url) looks quite interesting for me.
Can I try to solve it?
Bests,
Xudong

**Comment by yuanming-hu** [comment]
> BTW Is the talk gonna get recorded? I dont wanna stay up that late/wake up that early to look at them.



> +1, monday is a busy day to me. If we do screen recording then it's possible for college stduents like me to watch it later when they are ready, also helps people in different time zones.

Sure, recorded videos will be available on Bilibili. Thanks for asking.


@FantasyVR  Welcome! The math library #833  consists of a series of critical API design decisions. Let us know what you think about the current design. Thank you!

@Rullec Thanks! I'll add more details to #938.

**Comment by Eydcao** [comment]
If the crossProduct of 2D Vector is still needed I will take this one, seems okay for a rookie like me :>

**Comment by yuanming-hu** [comment]
Finally, GAMES 201 is close to the end. We got a lot of feedback from students, by kindly pushing them to use Taichi. Overall the feedback is very positive and people like it a lot.

Perhaps the most advantageous feature of Taichi is that people can easily run programs from someone else effortlessly. I don't think any other computer graphics programming system can achieve something like this.

I'm closing this issue now. A lot of thanks to everyone who made everything happen here!
