### ISSUE TITLE
[Opt] [ir] [refactor] Remove exceptions from IR passes

### ISSUE THREAD

**Issue by xumingkuan** [taichi-dev/taichi#1059]
Currently, we have many IR passes using the pattern of exception, and we want to get rid of it.

**How do we use exceptions now**
We `throw IRModified();` when the IR is modified, and catch it using some code like the follows:
```C++
ConstantFold folder;
while (true) {
  bool modified = false;
  try {
    node->accept(&folder);
  } catch (IRModified) {
    modified = true;
  }
  if (!modified)
    break;
}
```

**Why do we need to use exceptions**
I think the main reason comes from here:
```C++
void BasicStmtVisitor::visit(Block *stmt_list) {
  for (auto &stmt : stmt_list->statements) {
    stmt->accept(this);
  }
}
```

Whenever we erase a statement from or insert one to a block, all `std::vector::iterator`s of that block's `statements` may be invalidated. So we need to break all `for` loops like the above, and the most convenient way is to use exceptions.

**Why we want & how to get rid of exceptions**
Using exceptions is probably not a good coding style, and it may cause some incompatibility issues, as discussed in #655.

If we mark all modifications in IR optimization passes and do them together iteratively instead of modifying the IR and throw an exception as soon as we find an optimization opportunity, this will greatly reduce compilation time and solve #926.

**TODO list**
- [x] alg_simp (#1060, #1103)
- [x] check_out_of_bound (#1251)
- [x] constant_fold (#1251)
- [x] demote_atomics (#1272)
- [x] die (#1262)
- [x] extract_constant (#2966)
- [x] lower_access (#1292)
- [x] lower_ast (#3916)
- [x] offload (#3925)
- [x] simplify (high priority) (#3317)
- [x] <del>variable_optimization</del> (#3927)
- [x] whole_kernel_cse (#1131)

**Additional comments**
Shall we add the `noexcept` specifier to some functions known to not throw `IRModified`? Will it cause some issues with other exceptions?

**Comment by TH3CHARLie** [comment]
@xumingkuan I'd like to help with this. What would you suggest the proper size of a related PR? Should we use a single PR to refactor all TODO passes or maybe 3-4 passes in one PR?

**Comment by xumingkuan** [comment]
> @xumingkuan I'd like to help with this. What would you suggest the proper size of a related PR? Should we use a single PR to refactor all TODO passes or maybe 3-4 passes in one PR?

I think it's fine with only 1 pass in one PR. Different passes usually won't cause conflicts even if you open several PRs at the same time, and it might be error-prone if many passes are refactored in one PR.

**Comment by TH3CHARLie** [comment]
As I look through the `lower_ast` pass, I notice that:
https://github.com/taichi-dev/taichi/blob/42139736a971cf6dd77294b132ab4ed46fdeb718/taichi/transforms/lower_ast.cpp#L143-L145

> Note: Block::replace_with(Stmt *old_statement, std::unique_ptr<Stmt> &&new_statement, bool replace_usages) is safe even if we modify it directly and don't throw exceptions. So is Block::replace_with(Stmt *old_statement, VecStatement &&new_statements, bool replace_usages) only when new_statements->size() == 1.
>
I believe the code corresponds to your comment in #1272. But if we'll change the pass's signature to `bool`(so that the higher level logic would have no whether this pass modified IR), maybe we'd introduce some flag to denote that a change is made.

**Comment by xumingkuan** [comment]
Oh, for the specific pass `lower_ast`, it must modify the IR because it converts the frontend IR to the middle-end IR. So feel free to not change that pass's signature.

**Comment by xumingkuan** [comment]
@TH3CHARLie 
As https://github.com/taichi-dev/taichi/issues/926#issuecomment-645092561 addressed, `irpass::simplify` will take half of the compilation time after I remove the `variable_optimization` pass next week. So among the remaining passes, let's remove exceptions from the `simplify` pass first.

**Comment by yuanming-hu** [comment]
@xumingkuan IIRC the `simplify` pass is mostly CSE. Given that we have a whole program CSE pass that does a better job, should we first try to remove the CSE part of `simplify`?

**Comment by xumingkuan** [comment]
I think yes, and shall we replace `simplify` with `full_simplify` in `Simplified I`?

**Comment by yuanming-hu** [comment]
That sounds good. Thanks.

**Comment by TH3CHARLie** [comment]
> @TH3CHARLie
> As [#926 (comment)](https://github.com/taichi-dev/taichi/issues/926#issuecomment-645092561) addressed, `irpass::simplify` will take half of the compilation time after I remove the `variable_optimization` pass next week. So among the remaining passes, let's remove exceptions from the `simplify` pass first.

If I understand the conversations correctly, `simplify` will be refactored soon, so maybe I shouldn't do it?

**Comment by xumingkuan** [comment]
I think yes -- I'll try to remove the CSE part of `simplify` first.

**Comment by mzmzm** [comment]
It looks like that `variable_optimization` pass never be called anywhere. Maybe it can be removed from this project?

**Comment by strongoier** [comment]
> It looks like that `variable_optimization` pass never be called anywhere. Maybe it can be removed from this project?

I agree. It seems that its dependency, `StateMachine`, is also not used now. @xumingkuan wdyt?

**Comment by xumingkuan** [comment]
> > It looks like that `variable_optimization` pass never be called anywhere. Maybe it can be removed from this project?
> 
> I agree. It seems that its dependency, `StateMachine`, is also not used elsewhere now. @xumingkuan wdyt?

Agreed. The `variable_optimization` pass is an obsolete approach to `cfg_optimization` and we can remove it.
