### ISSUE TITLE
[CC] Ship the C backend!

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1644]
Continue our talk in #1332.

**Concisely describe the proposed feature**
Currently our C backend is capable of passing all the tests on my end. I think it's time to **officially release** the C backend!

**Describe the solution you'd like (if any)**
- [ ] Add C backend to per-submit CI (#1643, @archibate)
- [ ] Add a slot to `CompileConfig` to tweak compiler command so that people could choose their compilers & flags (@archibate)
- [ ] Add C backend to Linux buildbot (Jeksinsfile, @yuanming-hu)
- [ ] Add C backend to OS X buildbot (Travis CI, @k-ye)
- [ ] Add C backend to Windows buildbot (AppVeyor, @xumingkuan)
- [ ] Add documentation on the workflow exporting C source (https://github.com/taichi-dev/taichi/issues/920#issuecomment-668996612)
- [ ] Add documentation on [Taichi.js](https://github.com/taichi-dev/taichi.js) for play Taichi in browser (@archibate)
- [ ] Add documentation on how to call exported Taichi program in Julia (#1642, @samuela)

**Additional comments**

**Comment by samuela** [comment]
I just attempted the instructions [here](https://github.com/taichi-dev/taichi/issues/920#issuecomment-668996612) but I'm getting an error:
```
[I 08/09/20 23:44:16.054] [__init__.py:init@200] Following TI_ARCH setting up for arch=cc
[W 08/09/20 23:44:16.257] [__init__.py:adaptive_arch_select@383] Arch=Arch.cc is not supported, falling back to CPU
```
Am I doing something wrong?

**Comment by archibate** [comment]
Sorry, the C backend is not release yet. You need to clone the Taichi repo and build it from source.
Also note that currently the C backend is not compiled by default, please use `-DTI_WITH_CC:BOOL=ON` to override it:
```bash
cmake -Bbuild -S. -DTI_WITH_CC:BOOL=ON
make -Cbuild -j4
```

**Comment by samuela** [comment]
Ah, got it! I'll try building from source!

**Comment by samuela** [comment]
Awesome, so I now got TI_ARCH=cc working by editing the Dockerfile: #1680. Now I'm faced with a new issue:
```
root@425af79fc248:/difftaichi# TI_ACTION_RECORD=deleteme.yaml TI_ARCH=cc python3 examples/mass_spring.py 2 train
[Taichi] mode=development
[Taichi] preparing sandbox at /tmp/taichi-pdt02mkw
[I 08/10/20 22:13:05.615] [action_recorder.cpp:start_recording@27] ActionRecorder: start recording to [deleteme.yaml]
[Taichi] <dev mode>, llvm 10.0.0, commit bf403b58, python 3.6.9
[W 08/10/20 22:13:05.673] [shell.py:<module>@7] `sourceinspect` not installed!
[W 08/10/20 22:13:05.673] [shell.py:<module>@8] This may cause Taichi not functional in IDLE interactive shell, Blender scripting module and Python native shell.
[W 08/10/20 22:13:05.673] [shell.py:<module>@10] Please run `python3 -m pip install sourceinspect` to install.
[I 08/10/20 22:13:06.019] [__init__.py:init@208] Following TI_ARCH setting up for arch=cc
No protocol specified
[Taichi] Starting on arch=cc
n_objects= 20    n_springs= 46
[Taichi] materializing...
[I 08/10/20 22:13:07.144] [cc_program.cpp:compile_layout@137] [cc] C backend root buffer size: 9554712 B
[E 08/10/20 22:13:14.848] [statements.inc.h:visit@41] Not supported.


***********************************
* Taichi Compiler Stack Traceback *
***********************************
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::IRVisitor::visit(taichi::lang::LocalStoreStmt*)
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::MakeAdjoint::visit(taichi::lang::IfStmt*)
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::MakeAdjoint::visit(taichi::lang::Block*)
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::irpass::auto_diff(taichi::lang::IRNode*, bool)
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::irpass::compile_to_offloads(taichi::lang::IRNode*, taichi::lang::CompileConfig const&, bool, bool, bool, bool)
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::irpass::compile_to_executable(taichi::lang::IRNode*, taichi::lang::CompileConfig const&, bool, bool, bool, bool, bool, bool, bool)
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::cccp::CCTransformer::lower_ast()
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::cccp::CCTransformer::run()
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::cccp::CCKernelGen::compile()
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::cccp::compile_kernel(taichi::lang::Kernel*)
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::Program::compile(taichi::lang::Kernel&)
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::Kernel::compile()
/tmp/taichi-pdt02mkw/taichi_core.so: taichi::lang::Kernel::operator()()
/tmp/taichi-pdt02mkw/taichi_core.so(+0x48a1d9) [0x7fe360fa51d9]
/tmp/taichi-pdt02mkw/taichi_core.so(+0x3c6090) [0x7fe360ee1090]
python3(_PyCFunction_FastCallDict+0x35c) [0x566ddc]
python3() [0x594b71]
python3() [0x54ac61]
python3(_PyObject_FastCallKeywords+0x19c) [0x5a9eec]
python3() [0x50a783]
python3(_PyEval_EvalFrameDefault+0x444) [0x50c1f4]
python3() [0x507f24]
python3() [0x588ddb]
python3(PyObject_Call+0x3e) [0x59fe1e]
python3(_PyEval_EvalFrameDefault+0x17e6) [0x50d596]
python3() [0x507f24]
python3(_PyFunction_FastCallDict+0x2e2) [0x509202]
python3() [0x594b01]
python3() [0x54ac61]
python3(PyObject_Call+0x3e) [0x59fe1e]
python3(_PyEval_EvalFrameDefault+0x17e6) [0x50d596]
python3() [0x509918]
python3() [0x50a64d]
python3(_PyEval_EvalFrameDefault+0x444) [0x50c1f4]
python3(_PyFunction_FastCallDict+0xf5) [0x509015]
python3() [0x594b01]
python3(_PyObject_FastCallDict+0x17c) [0x5a4a0c]
python3(PyObject_CallFunctionObjArgs+0xd8) [0x5a50d8]
python3(_PyEval_EvalFrameDefault+0x1af3) [0x50d8a3]
python3() [0x507f24]
python3() [0x509c50]
python3() [0x50a64d]
python3(_PyEval_EvalFrameDefault+0x1226) [0x50cfd6]
python3() [0x509918]
python3() [0x50a64d]
python3(_PyEval_EvalFrameDefault+0x444) [0x50c1f4]
python3() [0x507f24]
python3(PyEval_EvalCode+0x23) [0x50b053]
python3() [0x634dd2]
python3(PyRun_FileExFlags+0x97) [0x634e87]
python3(PyRun_SimpleFileExFlags+0x17f) [0x63863f]
python3(Py_Main+0x591) [0x6391e1]
python3(main+0xe0) [0x4b0dc0]
/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
python3(_start+0x2a) [0x5b26fa]

Internal Error occurred, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "examples/mass_spring.py", line 390, in <module>
    main()
  File "examples/mass_spring.py", line 384, in main
    optimize(toi=True, visualize=False)
  File "examples/mass_spring.py", line 321, in optimize
    forward(visualize=visualize)
  File "/taichi-dev/taichi/python/taichi/lang/tape.py", line 18, in __exit__
    self.grad()
  File "/taichi-dev/taichi/python/taichi/lang/tape.py", line 27, in grad
    func.grad(*args)
  File "/taichi-dev/taichi/python/taichi/lang/kernel.py", line 499, in __call__
    return self.compiled_functions[key](*args)
  File "/taichi-dev/taichi/python/taichi/lang/kernel.py", line 461, in func__
    t_kernel()
RuntimeError: [statements.inc.h:visit@41] Not supported.
root@425af79fc248:/difftaichi# 
```
Does the CC backend not support gradients?

**Comment by archibate** [comment]
> Does the CC backend not support gradients?

Yes, that example probably needs `adstack`, which is not yet implemented on CC. I'll try to add it in the future.

**Comment by samuela** [comment]
Ah ok, I really need the AD system, so I'll try using taichi through PyCall.jl then for the time being.
