### ISSUE TITLE
v0.8.0 Roadmap

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#1847]
**Workflows**
 - [ ] Automatic release (#1674, lead: @rexwangcc)
 - [ ] Enforce code header (#1024, TODO: automatically check copyright info existence)
 - [ ] Codecov or something else to cover C++17 (lead: @archibate)
 - [ ] Set up `pylint` (#1846, lead: @archibate)
 - [ ] Set up `Cpplint`

**Python frontend**
 - [ ] Move frontend to Python (#925)
 - [ ] Blender intergration (#1773, [Taichi-Blend](https://github.com/taichi/taichi_blend), lead: @archibate)
 - [ ] Move to multi-pass Python AST transformer (lead: @archibate)
 - [ ] Possible Python 2.7 support (#1842, lead: @archibate)

**IR system**
 - [ ] Expose CHI C++ API
 - [ ] Remove `get_current_program` (#988)
 - [ ] IR standardization (#689)
 - [ ] Remove C++ exceptions
 - [ ] Refactor `gather_statements`
 - [ ] Real function support (#602, lead: @archibate)

**Sparse computation**
 - [ ] `hash` SNode
 - [ ] `bitmasked` garbage collection
 - [ ] `ti.append` support multiple child (#1282, lead: @archibate)
 - [ ] Non-POT internal nodes are not allowed

**Backends**
 - [ ] Create a fresh new Context for args+earg+rets per-launch (#1739, lead: @k-ye)
 - [ ] JS/WASM backend ([Taichi.js](https://github.com/taichi/taichi.js), lead: @archibate)
 - [ ] AMDGPU backend (lead: @masahi)
 - [ ] Restore vectorization on LLVM CPUs (lead: @yuanming-hu)
 - [ ] Improve float atomic performance on LLVM CPUs (#1752)
 - [ ] Multi-GPU or distributed computation support

(Feel free to add/lead items as you wish.)

**Comment by yuanming-hu** [comment]
First of all, thank you for putting together this list.

However, I don't think items here can be realistically implemented in a minor version. Prioritization and making realistic plans are vitally important.

Also note that we are still working on v0.7 (#677). Let's keep things simple and stick to one roadmap at a time. 

Long-term planning (including creating roadmaps) is my job (instead of someone else's). Having a single, consistent person making crucial decisions is beneficial to the health of the Taichi project.

Thanks again, but I have to close this issue to avoid confusing other developers. After v0.7 is released, I'll open a new roadmap for v0.8.
