### ISSUE TITLE
[Roadmap] Long-term plan

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1988]
### Minor version schedule

| Version | [0.7](https://github.com/taichi-dev/taichi/issues/677) | [0.8](https://github.com/taichi-dev/taichi/projects/6)      | 0.9      | 1.0 |
|---------|----------|----------|----------|-----|
| Date    | Oct 2020 | **July 2021** | Jan 2021 | TBD |

We will leverage [GitHub projects](https://github.com/taichi-dev/taichi/projects) to track minor version progress.

### Long-term TODO items
- [ ] IR standardization (#689)
- [ ] `hash` SNode
- [ ] `bitmasked` garbage collection
- [ ] AMDGPU backend
- [ ] Restore vectorization on CPUs
- [ ] Real function support (related: #602)
- [ ] Move frontend to Python (#925)
- [ ] Expose CHI C++ API
- [ ] Codecov or something else to cover C++17 linting
- [ ] Remove C++ exceptions
- [ ] Multi-GPU or distributed computation support

**Comment by rexwangcc** [comment]
+1 for leveraging the Github projects to track the progress! Since it provides a borad view, would it make sense to add invidivual issues to the board as well? E.g. I would expect to see all issues in the to-do column of v8 board rather than the pinned v8 one.
![Screen Shot 2020-10-22 at 7 35 04 PM](https://user-images.githubusercontent.com/14366016/96940440-b8560c00-149d-11eb-8bd0-3c66c01b88ba.png)

(nvm if it's already on your radar)

**Comment by yuanming-hu** [comment]
Great idea! I should have done that. I added a few known issues there. Please feel free to add more when deemed appropriate :-)

**Comment by ailzhang** [comment]
Closing this issue for now, please refer to https://github.com/taichi-dev/taichi/issues/2398 for a up-to-date version of our one year roadmap.
