### ISSUE TITLE
[Roadmap] v0.8

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#1989]
## **This roadmap is deprecated. Please see https://github.com/taichi-dev/taichi/issues/2398 instead :-)**

<strike>

- [ ] Migrate documentation to the [new website](https://taichi.graphics/) (coordinator: @rexwangcc )
- [ ] Enforce code copyright info
   - [x] Implement a script to add and check copyright info (#1024)
   - [ ] Set up a GitHub workflow to automatically check copyright info existence for every PR
   - [ ] Use @taichi-gardener to create a PR and add copyright info to all files
- [ ] Automatic release (#1674, lead: @rexwangcc)
- [ ] Platform-independent wheel (#1987, lead: @archibate)
- [ ] Update issue templates (We need a `refactor` template)
- [ ] Shrink the `misc` folder
   - Completely remove that folder may not be possible since we do need a temporary folder to store files that do not belong everywhere else
- [ ] Set up `pylint`
   - [x] A good start is #1846 (nicely done by @archibate)
   - We may need to think about how to continuously enforce Python linting using GitHub workflows
- [ ] Remove `get_current_program` (#988)
- [ ] `ti format` command should not need to `import taichi`
   - Otherwise, the format server will fail frequently, since it never compiles `taichi_core` when triggered and there is a mismatch between Python scripts and `taichi_core`. 
- [x] Non-POT internal nodes should no longer be allowed
- [x] Update `README.md` (lead: @yuanming-hu)
   - Update large-scale examples and contributors
- [x] Create a fresh new Context for args+earg+rets per-launch (#1739, lead: @k-ye)
- [ ] Improve namespaces 
   - Do we really need `taichi::lang`?
   - It may also make sense to replace `taichi::lang` with `taichi::ir`, `taichi::backend` etc.
   - Remove macros `TLANG_NAMESPACE_BEGIN`/`TI_NAMESPACE_BEGIN`?
- [ ] Refactor `gather_statements` (lead: @k-ye)
   - It seems what we really need is a "MapReduce" on the IR. `gather_statements` is often abused to achieve something else
- [x] Support `pointer` on Metal (#1740, lead: @k-ye)
- [x] Merge AppVeyor and Travis CI tasks so that we pay fewer dollars
- [x] Vulkan backend

To lead the implementation of an item, please open up an issue, briefly describe the implementation plan, and wait for an approving response from one of the [TSC members](https://taichi.graphics/community/members.html#technical-steering-committee).

The roadmap lists our top-priorities and will be dynamically adjusted. We do encourage contributors to propose other items that they are interested in :-)

</strike>
