### ISSUE TITLE
One-Year Roadmap

### ISSUE THREAD

**Issue by k-ye** [taichi-dev/taichi#2398]
Hi,

We are sharing this one-year road map to let you know what features are planned ahead or have been actively worked on. Hopefully some of these sound interesting/exciting! Let us know what you think so that we can adjust accordingly. Thanks!  

---

## New Features

* [x] Allow adding and deleting new SNodes dynamically (#2418, #2506)
    * Phase 1: LLVM
    * Phase 2: the rest
* [x] Make Taichi's JIT kernels deployable without the Python execution environment (https://github.com/taichi-dev/taichi/issues/2355)
   * https://github.com/taichi-dev/taichi/pull/3908
* [ ] Provide a way for Taichi to pass data with other frameworks (https://github.com/taichi-dev/taichi/issues/2380)
* [x] Support vector/matrix dynamic indexing (https://github.com/taichi-dev/taichi/issues/1004)
* [x] Systematic IR type system
* [ ] (Hard) Real function support (https://github.com/taichi-dev/taichi/issues/602)
* [x] Refactor the compilation workflow so that user-program errors are properly and clearly reported
   * Annotate the IRs with its source code location

## Backends

* [x] Vulkan backend support (https://github.com/taichi-dev/taichi/issues/2298)
* [x] Support `pointer` on Metal (https://github.com/taichi-dev/taichi/issues/1740)
* [ ] Other backends Including DX, WASM, OpenCL, etc (https://github.com/taichi-dev/taichi/issues/992)
* [x] Create a unified backend interface (#2736)
    * [x] Decouple `Program` from each backend
    * [ ] Have a uniform layer for data transfer and device to host synchronization (https://github.com/taichi-dev/taichi/issues/2344)

## Performance

* [ ] Speed up the JIT compilation time by parallel compilation
* [ ] Optimize the GPU backend performance in certain scenarios (https://github.com/taichi-dev/taichi/issues/2324, https://github.com/taichi-dev/taichi/issues/2395)
* [x] Continuous regression tests for the GPU backends
* [ ] Simplify the condition to use BLS
* [x] Accelerate `import taichi`
   * The `ti` CLI should only import `taichi` when necessary

## Documentation

* [x] Add Python docstring for the public APIs (#2579)
* [ ] Add documentation for the essential C++ APIs (e.g. `Program`, `Kernel`)
* [x] Automatically generate the documentation webpages from the Python/C++ API documentation.

## Cleanups

* [ ] Codebase refactoring
    * [ ] Remove the global variables, especially the global program and the frontend AST context (https://github.com/taichi-dev/taichi/issues/988)
    * [x] Clean up the frontend AST transformer
    * [ ] Simplify the C++ `Expr`, `Expression` classes and the Python `Expr` class.
    * [x] `ti.field` should return an instance of either `SNode` instance or a dedicated field class (Currently it returns an `Expr`).
    * [x] Simplify `ti.Matrix` and `ti.Vector`
* [x] Modularize the `taichi` package hierarchy (https://github.com/taichi-dev/taichi/issues/2223)
    * Do not expose everything to the top-level namespace.
* [x] Control the symbol visibility of `libtaichi_core.so` and remove the linker script
* [ ] Deprecate `TI_NAMESPACE_{BEGIN, END}`

## Release

* [x] Release to Python 3.9 (https://github.com/taichi-dev/taichi/issues/2359)
* [x] Release to Apple M1 (https://github.com/taichi-dev/taichi/issues/2254)
* [ ] Separate `taichi` and `taichilib` release (https://github.com/taichi-dev/taichi/issues/2351)
    * This makes `taichi` platform-independent (https://github.com/taichi-dev/taichi/issues/1987)

## CI/Productivity

* [ ] CI presubmit improvements
    * [x] Automatically and reliably format the code in the PR (https://github.com/taichi-dev/taichi/issues/2369)
    * [x] Cancel the previous workflow when a new commit is pushed (https://github.com/taichi-dev/taichi/issues/2202)
    * [x] Set up py/cpp linter in CI presubmits (https://github.com/taichi-dev/taichi/issues/2624)
    * [ ] Dockerize the CI environments
* [x] Reduce the number of CI platforms in use
    * [x] Try to get rid of Appveyor
* [ ] Enforce license header for each source code file
* [x] Provide a conda environment config file that automatically sets up the developer installation steps.
* [ ] Move CI related scripts to `ci/`

---

In addition, the items below are also on our radar, but we haven't thought about too much yet:

* Polish the autodiff system
   * Either remove/relax the Kernel Simplicity Rule, or provide a concrete error message explaining why the kernel breaks.
* Modularize the C++ codebase
    * Ensure that the codebase has no circular dependencies (https://github.com/taichi-dev/taichi/issues/2203)
    * Make this a required status check before merging
    * Ideally, build the logically-related source files into its own static library.
* Provide a more intuitive way for the users to leverage GPU shared memory
    * Rationale: If they know what shared memory is, they probably are experienced GPU programmers and care about the performance (over productivity).
* Productionize the async engine
* Support LLVM 12 https://github.com/taichi-dev/taichi/issues/3281
* Restore CPU vectorization
* Fault-tolerance + checkpointing
* Isolating CHI IR into its standalone library. However, this work are blocked on several aforementioned items:
   * modularize the C++ codebase
   * real function support
   * C++ symbol visibility
You

**Comment by ifsheldon** [comment]
For the point of polishing the autodiff system, I think this kernel simplicity rule comes from the "reverse replay" (if you will call it like this) of Autodiff, if I remember the DiffTaichi paper correctly. With kernel simplicity rule, in the "reverse replay" phase, each inner iteration can have a concrete compute graph that is not dependent on anything in the outerloop iterations (since we cannot have anything in the outerloop iterations).
For example, we have nested loops like this
```python
@ti.kernel
def broadcast_add_bad(array0: ti.template(), array1: ti.template(), matrix: ti.template()):
    for i in array0:
        num0 = array0[i]
        for j in array1:
            num1 = array1[j]
            matrix[i, j] = num0 + num1

@ti.kernel
def broadcast_add_good(array0: ti.template(), array1: ti.template(), matrix: ti.template()):
    for i in array0:
        for j in array1:
            num0 = array0[i]
            num1 = array1[j]
            matrix[i, j] = num0 + num1
```
Suppose we have 2 10-element arrays, then we will have 100 iterations. In the bad example, we will have 10\*10 inner loop iterations bundled with 10 `num0`s, but in the good example, we can have independent 100 iterations.
From my guess of "reverse replay", it's understandable to have such a rule. Moreover, I think this rule actually originates from this design choice mentioned in the diffTaichi paper.
> a light-weight tape that only stores function pointers and arguments for end-to-end simulation differentiation 

but if you want to relax or even remove the kernel simplicity rule, you have to record more information in the tape. For this example, the tape need to record that 10 inner loop iterations are bundled to a `num0`. This may lead to a complete redesign of the tape and it's non-trivial I guess.

I don't know if this will help or if you know this, but you can check out Julia Flux's Zygote, which is for source-to-source AD. The link to its paper is [here](https://arxiv.org/abs/1810.07951). Flux can handle AD on complex control flows in Julia programs, and if you consider a kernel instance of a thread of a "Julia program", then maybe you can transfer the idea of Zygote to Autodiff.

**Comment by k-ye** [comment]
Hi there,

Taichi has finally made its [v1.0.0](https://github.com/taichi-dev/taichi/releases/tag/v1.0.0). We will follow the semver and make minor version bumps for feature releases. The next minor release will be [v1.1.0](https://github.com/taichi-dev/taichi/milestone/5). Closing this one now.

**Comment by shift6666** [comment]
> In addition, the items below are also on our radar, but we haven't thought about too much yet:
> 
> * Polish the autodiff system
>   
>   * Either remove/relax the Kernel Simplicity Rule, or provide a concrete error message explaining why the kernel breaks.
> * Modularize the C++ codebase
>   
>   * Ensure that the codebase has no circular dependencies ([Reduce the C++ compilation duration #2203](https://github.com/taichi-dev/taichi/issues/2203))
>   * Make this a required status check before merging
>   * Ideally, build the logically-related source files into its own static library.
> * Provide a more intuitive way for the users to leverage GPU shared memory
>   
>   * Rationale: If they know what shared memory is, they probably are experienced GPU programmers and care about the performance (over productivity).
> * Productionize the async engine
> * Support LLVM 12 [Upgrade to LLVM12 #3281](https://github.com/taichi-dev/taichi/issues/3281)
> * Restore CPU vectorization
> * Fault-tolerance + checkpointing
> * Isolating CHI IR into its standalone library. However, this work are blocked on several aforementioned items:
>   
>   * modularize the C++ codebase
>   * real function support

Hello, if there are any code examples available in Taichi about checkpointing that could help me learn and refer to?
