### ISSUE TITLE
AOT use cases in CI tracker

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#5432]
Currently we have multiple use cases of taichi aot scattered in different repos, this issue aims to track the progress of adding them in taichi CI before v1.1 release: 

- [ ]  https://github.com/taichi-dev/Taichi-UnityExample 
  - [ ] fractal
  - [x] implicit_fem
  - [ ] (TBA?) mpm88
- [ ] https://github.com/taichi-dev/taichi-aot-demo
  - [x] implicit_fem android demo
