### ISSUE TITLE
Opengl aot support tracking issue

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#5769]
related: #5634 

We'll use this issue to track progress in opengl aot support. 

To give some context, we removed opengl codegen and moved it on top of spirv codegen in #5246 which relieves our burden to maintain multiple codegens. But we haven't migrated or provided a runtime library (like what we did for vulkan backend) to run our android app yet. 

After migrating on top of spirv, opengl aot actually can benefit a lot from the common gfx runtime and we just need to complete the following milestones:

- [ ] Fix existing buggy opengl aot tests 
- [ ] Expand python aot tests to cover opengl backend
- [ ] Expand cpp aot tests to cover opengl backend
- [ ] Run implicit_fem desktop demo on top of opengl backend
- [ ] Make sure `use_gles` is properly handled and run implicit_fem android demo

And ofc, we will fix whatever pops up when we try to accomplish the milestones above ;)
