### ISSUE TITLE
Refactor kernel compilation

### ISSUE THREAD

**Issue by PGZXB** [taichi-dev/taichi#7002]
(This is part of **_Refactor kernel compilation and launch_**, which aims to split kernel compilation and kernel launching totally.)

### Brief Introduction
1. Isolate the stuff which is not related with kernel compilation from `lang::Kernel`.
2. **`lang::CompileConfig` per compilation** instead of `lang::CompileConfig` per `lang::Program`.
3. Introduce `lang::CompiledKernelData`, `lang::KernelCompiler` to **unify** the compilation result and the interfaces of kernel compilation.
4. Introduce `lang::KernelCompilationManager` to unify the implementation of _cache_ on **ALL** backends, including _online cache_ and _[offline cache](https://github.com/taichi-dev/taichi/issues/4401)_
5. Re-impl the JIT in Python frontend and remove the _online cache_ in frontend 

### Prototype
* An **incomplete** implementation of this proposal: see https://github.com/taichi-dev/taichi/pull/6819 or [PGZXB:dev-refactor-kernelCR-1st-prototype](https://github.com/PGZXB/taichi/tree/dev-refactor-kernelCR-1st-prototype)

### Provide `@ti.pkernel`
> _**NOTE:** The `@ti.pkernel` is **only an attempt** based on the prototype in order to **verify the effect of the proposal**, which is **NOT** a "feature request"._

* `@ti.pkernel` = `@ti.kernel` + `CompileConfig`, which allows the user to specify different compile configuration options for each kernel.
#### Implementation
* See [PGZXB:dev-pkernel-based_on-refactorKCaL_1st_prototype](https://github.com/PGZXB/taichi/tree/dev-pkernel-based_on-refactorKCaL_1st_prototype)
  
#### Example
```python
import taichi as ti

ti.init(arch=ti.vulkan, offline_cache=True, print_preprocessed_ir=False)

@ti.kernel
def K1(a: ti.i32, b: ti.i32) -> ti.i32:
  return a + b


@ti.pkernel(offline_cache=False, print_preprocessed_ir=True)
def PK1(a: ti.i32, b: ti.i32) -> ti.i32:
  return a * b

# Not allowed before finishing "Refactor kernel launch"
# @ti.pkernel(arch=ti.cpu) # ti.cpu != ti.vulkan
# def PK2(a: ti.i32, b: ti.i32) -> ti.i32:
#   return a * b

K1(10, 10)
PK1(10, 10)
# PK2(10, 100)
```

### To-Do List

- [x] Remove dependencies on Program::current_ast_builder() in C++ side, see prototype: 73e5b7119277928b70a93c8557d06be3c39b5c97
- [x] Remove Program::current_ast_builder(), see prototype: 0b301408a099d655fcbf07280837c766216be5d1
- [x] Remove Program::current_callable, see prototype: f6d5a55273f761fa03873d52100c6004c5e2c3dd; fdd230f3cb8e2dc2f4884c946f2ee9390cd1bbff
- [x] Remove Kernel::arch
- [x] Remove Kernel::lower & Add irpass::ast_to_ir, see prototype: 6a83c69d46f018a789e8801feae745a4636a6bc0; a77e46a5a0fb16ba061ea3b67be461d530b87c5c
- [x] Remove CompileConfig::lazy_compilation, see prototype: b82cd7dbda7e3935634d4287bc33a08fae4f0d3b
- [x] ~~Move Kernel::compile and Kernel::operator() outside, see prototype: b5d6bebb86216e28eb243ac441c0042f0990a44f~~
- [x] Rename arg to param in class Callable, see prototype: b943d3d
- [x] ~~Refactor Kernel::get_ret*, see prototype: d87a8bab6f18087aeb9b8915a2858fcbe7206326; 80bea8976d7874d305bf181e8970431b924dafe1; 732b4a3fa574905aa613daaaa7b0987bc4c025f0; 0920501cfae6c261918bc666f9998f3042063baa; 0f2a0b58dc5dac46dfd6a483c3bbb17cf16324cb; 7eb13d5d7e290fe9e3dca667f0db3d577725064a~~
- [x] Remove dependencies on Program::this_thread_config() in metal::CacheManager, see prototype: e595513ba21169e3a11de0b47a16006bbf37ea8e
- [x] Remove offloaded parameter of Program*::compile, see prototype: 582f287fe4a54c2ba719be6c31e3e9c5e4360b87
- [x] Remove ir parameter in KernelCodeGen::KernelCodeGen(Kernel *kernel, IRNode *ir), see prototype: a2f1e151fa801e987c8d3ecc8fc08c81e8cb31c9
- [x] Remove dependencies on Program::this_thread_config() in KernelCodeGen, see prototype: 187f206bb21f26dcd411827448358ea16b51511e
- [x] Remove dependencies on Program::this_thread_config() in codgen on llvm backends, see prototype: 423a29c7156e829e62739e047fa383bb4b36518d; 8ecf111f444d6d4ec520fbcb7fb46029247bc105; b8deaf01ed83e595328b2d0b7446ecf18a7c5d25
- [x] Remove dependencies on Program::this_thread_config() in irpass::scalarize, see prototype: 40d4b33ee867da867232691aa311a0f44bcce960
- [x] Remove dependencies on Program::this_thread_config() in gfx/runtime.cpp, see prototype: 2120e4330d426f8023e968b5e529b8026a464ba1; 53d9e8eadbf4e4df8ed14a9409f73fbed9242e0e
- [x] Remove dependencies on Program::this_thread_config() in spirv::lower, see prototype: 79b4b9a4a465eeb4e1e368ae3c6ccedfbe4dbfce
- [x] Remove dependencies on Program::this_thread_config() in codegen_cc.cpp, see prototype: 19d6e11e644cedbe6bca912abc5e1c56a2e582f5
- [x] Remove IRNode::get_config, IRNode::get_kernel and IRNode::kernel, see prototype: 592f7982ab78bb69915b7c8dac2181854aaa9b10; 72b23df6eb46b4dc66e70dccf862725a1ba6031c
- [x] Remove dependencies on Program::this_thread_config() in lang::launch_kernel(), see prototype: 1f958a3f212d236e734470025f5452bebc07329f; f9de0fe3cca010b316035cffb3d2ac6e8885955f
- [x] Remove dependencies on Program::this_thread_config() in constant folding & rm possible race condition, see prototype: 2571bf9af29a1dcff01f8c9d2cdad26daa316e1e; 3164640b11d2cae73bac4b513d1576cc1ba4e3da
- [x] Remove Program::this_thread_config() & Add Program::global_compile_compileconfig(), see prototype: abcff079a8cf6891293bfb9d21e629dbb8e202d6
- [x] Split lang::Function, see prototype: d87e6d903cdbe10c28311486e877f134b1ad56fc
- [x] Implement irpass::clone for AST
- [x] Introduce CompiledKernelData & KernelCompiler & KernelCompilationManager, impl them for spirv/gfx backends and re-impl VulkanProgramImpl::compile() and gfx::AotModuleBuilder, see prototype: 40e9751fdb24399e881ec38a366a3a11861ca438; c8e62853b53e522349b04492cfc0c619017cdb82; 0697032cf0593a8135a7b731686fcdff30ec1224
- [x] #7311
- [x] Intorduce CompiledKernelData & KernelCompiler for LLVM backends (**Hard**)
- [x] Intorduce CompiledKernelData & KernelCompiler for Metal backends
- [x] Fix implementation of JIT in Python-frontend: t_kernel(ctx) -> load_or_compile(...) && prog.launch_kernel(...)
- [x] Remove online cache in Python side (`PyTaichi.compiled_functions`)
- [ ] Redesign the algorithm to generate the offline cache key for real_funcs (to fix #6877)
- [x] ~~#7286~~
- [x] Fix all `const CompileConfig *` to const CompileConfig &`
- [x] Remove Kernel::from_cache_
- [x] Remove Kernel::task_counter_
- [x] Remove useless Kernel::lowered_

### Related work
* Maybe start [replacing pybind11 with XXXXXX](https://github.com/taichi-dev/taichi/issues/6395) from the APIs about kernel compilation and launch. Some of them will be refactored and standardized in this proposal.
