### ISSUE TITLE
Remove lang::Callable::program

### ISSUE THREAD

**Issue by PGZXB** [taichi-dev/taichi#7286]
(Part of #7002)
### ToDo-List
- [x] Remove dependencies on Callable::program in `lang::get_hashed_offline_cache_key()`
- [x] Remove dependencies on Callable::program in `CompiledGraph::run`
- [ ] Remove dependencies on Callable::program in `KernelCodeGen` (by removing `KernelCodeGen::prog`)
- [ ] Remove dependencies on Callable::program in `TaskCodeGenLLVM` (by removing `TaskCodeGenLLVM::prog`)
- [ ] Remove dependencies on Callable::program in kernel launching
- [ ] Remove dependencies on Callable::program in exported `Kernel.__call__`
- [x] Remove dependencies on Callable::program in `constant_fold` (by https://github.com/taichi-dev/taichi/pull/7661)
- [x] Remove dependencies on Callable::program in some tests
- [ ] Remove `Callable::program`
