### ISSUE TITLE
compile - runtime split for `TaichiLLVMContext`

### ISSUE THREAD

**Issue by PGZXB** [taichi-dev/taichi#7311]
(Part of #7002)
### ToDo-List
 - [ ] `TaichiLLVMContext::jit` -> `LlvmRuntimeExecutor::jit_session_`
    - [x] Move `JITSession::global_optimize_module` to `KernelCodeGen`
    - [x] Use `TaichiLLVMContext::get_data_layout_()` instead of `JITSession::get_data_layout()` (add `TaichiLLVMContext::data_layout_`)
    - [x] `TaichiLLVMContext::create_jit_module()` -> `LlvmRuntimeExecutor::create_jit_module()`
    - [x] Remove `TaichiLLVMContext::lookup_function_pointer()` (use `JITModule::lookup_function()` instead of `TaichiLLVMContext::lookup_function_pointer()`)
  - [x] `TaichiLLVMContext::runtime_jit_module` -> `LlvmRuntimeExecutor::runtime_jit_module_`

We need to finish the work before introducing `KernelCompilationManager`. 

Thanks @jim19930609's comment:
https://github.com/taichi-dev/taichi/blob/98b8be4920868c7e0b4ea2ed2a20c51ec2e61ff5/taichi/runtime/llvm/llvm_runtime_executor.h#L132-L136
