### ISSUE TITLE
[Tracking issue] Pain points when interacting with external framework (Numpy/PyTorch)

### ISSUE THREAD

**Issue by ailzhang** [taichi-dev/taichi#7780]
This issue serves tracking purpose for all issues related to user experience when interacting with external framework like Numpy and PyTorch. 

- [ ] Extra copy if a non-contiguous torch tensor / numpy array is passed into taichi kernels.
  - We'll need better support for strided tensors at least. 
 
- [ ] Taichi preallocates GPU memory chunk which may conflict with PyTorch's heavy GPU memory usage.
  - configurable by `ti.init` but it's better to get rid of preallocation if possible

- [ ] Support ndarray autodiff so that we can let taichi kernels directly operate on torch's primal and grad tensors.

**Comment by oliver-batchelor** [comment]
Forgive me hijacking an unrelated issue - but I have another couple:
- Can't access dtype in the kernel/function as you could with a field
- Cannot include external arrays in templates, so for example you cannot have a tuple of arrays (which you can with fields)

**Comment by ailzhang** [comment]
@oliver-batchelor No worries at all! Your feedback is pretty valuable to us and this issue is indeed the right place to add them! I'll keep your issues in mind when thinking about the refactor plan and get back to you when I have a proposal!

**Comment by chenzhekl** [comment]
+1 for accessing `dtype` of `ndarray` in Taichi scope. This is super useful when writing amp-compabitle codes.
