### ISSUE TITLE
[gui] visualization utilities for debugging

### ISSUE THREAD

**Issue by chunleili** [taichi-dev/taichi#7853]
## The proposed features

We are goning to provide some visualization utilities which helps users debug. These utilities are built upon the existing functionalities of taichi GGUI/GUI, and will not go deep into the vulkan backend etc. 

## Roadmap

- [ ]  Matrix checker
  - [ ] It should show the pattern of a sparse matrix, like the `spy()` function in `scipy` or `MATLAB`. 
  - [ ] It should show the value of the matrix, with capability of zoom in/out
  - APIs:
- [ ] Particles/faces selector
  - [ ] By drawing a rectangle with mouse, it should return the ids of the particles/faces.
  - [ ] It should have two modes: penatration mode and surface selection mode, like paraview.
  - APIs: 
- [ ] Sparse grid visualizer
  - [ ] It should show the activated sparse grid with wireframed box, like Houdini.
  - APIs: 

@houkensjtu
