### ISSUE TITLE
[RFC] Add MLIR dialect for taichi IR

### ISSUE THREAD

**Issue by python3kgae** [taichi-dev/taichi#7886]
## The proposed features

Add MLIR dialect for tachi IR to leverage MLIR Ecosystem. 

## Roadmap

- Update LLVM in taichi
  - [ ] Update to latest LLVM to use latest MLIR.

- Add MLIR dialect for Taichi Hierarchical SSA IR
  - [ ] Add the dialect. We can call it Taichi Hierarchical SSA dialect.
  - [ ] Insert the dialect between Taichi Hierarchical SSA IR and stage after it.
  - [ ] Port optimizations on Taichi Hierarchical SSA IR to MLIR.
  - [ ] Remove optimizations on Taichi Hierarchical SSA IR.
 
- Add MLIR dialect for Taichi Frontend AST IR
  - [ ] Add the dialect. We can call it Taichi Frontend AST dialect.
  - [ ] Insert the dialect between Taich Frontend AST IR and Taichi Hierarchical SSA dialect.
  - [ ] Remove Taichi Hierarchical SSA IR.
  - [ ] Lower Taichi AST to Taichi Frontend AST dialect.
  - [ ] Remove Taichi IR.

**Comment by bobcao3** [comment]
Don't think we should go this route... Lots of current problems can be solved with a similar level of engineering effort, and doing so basically ties us with LLVM and its development cycles.

**Comment by python3kgae** [comment]
> Don't think we should go this route... Lots of current problems can be solved with a similar level of engineering effort, and doing so basically ties us with LLVM and its development cycles.

We already depends on LLVM. And we don't need to update when  LLVM update unless there're features we need.
This RFC doesn't solve any problem, it just open the door to MLIR.

**Comment by bobcao3** [comment]
We don't depend on LLVM. The GFX backends are entirely LLVM free. We even have a flag to compile without LLVM

**Comment by python3kgae** [comment]
> We don't depend on LLVM. The GFX backends are entirely LLVM free. We even have a flag to compile without LLVM

I see. Then is it possible to only add MLIR when TI_WITH_LLVM is ON?

**Comment by DocSavage** [comment]
@bobcao3 So far, I'm finding the particular domain-specific accelerations and language features (e.g., sparse spatial access) to be quite compelling. I do wonder about ease of integrating deep learning components (e.g., how the iNGP implementation moved between pytorch and taichi). In particular, I wonder if we could ever get something like Taichi + Mojo (both Python++) where Mojo seems to be implementing a lot of their features through MLIR, assuming their stuff goes open source at some point.
